### ISSUE TITLE
Check for existing subscriptions throws a TypeError

### ISSUE THREAD

**Issue by jkhoel** [jkhoel/notius-ui#8]
`TypeError: Cannot read property 'subscriptions' of null
    at Operation.componentWillReceiveProps (http://localhost:3000/static/js/bundle.js:57477:28)
    at http://localhost:3000/static/js/bundle.js:28504:24
    at measureLifeCyclePerf (http://localhost:3000/static/js/bundle.js:27968:13)
    at ReactCompositeComponentWrapper.updateComponent (http://localhost:3000/static/js/bundle.js:28503:10)
    at ReactCompositeComponentWrapper.receiveComponent (http://localhost:3000/static/js/bundle.js:28440:11)
    at Object.receiveComponent (http://localhost:3000/static/js/bundle.js:19968:23)
    at Object.obj.(anonymous function) [as receiveComponent] (chrome-extension://fmkadmapgofadopljbjfkapdkoienihi/build/backend.js:8537:20)
    at Object.updateChildren (http://localhost:3000/static/js/bundle.js:27704:26)
    at ReactDOMComponent._reconcilerUpdateChildren (http://localhost:3000/static/js/bundle.js:27238:33)
    at ReactDOMComponent._updateChildren (http://localhost:3000/static/js/bundle.js:27342:32)`

Does not break the page, but needs to be resolved

**Comment by jkhoel** [comment]
fixed
